/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "VozSegura",
  "tagline": "Ambiente digital inclusivo, seguro e participativo para 60+",
  "url": "https://DavidDeodato.github.io",
  "baseUrl": "/vozsegura-docs/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "DavidDeodato",
  "projectName": "vozsegura-docs",
  "themeConfig": {
    "navbar": {
      "title": "VozSegura",
      "logo": {
        "alt": "VozSegura logo",
        "src": "https://raw.githubusercontent.com/DavidDeodato/vozsegura-docs/main/docs/logo_sem_fundo_sem_nome_embaixo.png"
      },
      "items": [
        {
          "to": "/docs/index",
          "label": "Sumario Executivo",
          "position": "left"
        },
        {
          "to": "/docs/entendimento-problema",
          "label": "Problema",
          "position": "left"
        },
        {
          "to": "/docs/solucao",
          "label": "Solucao",
          "position": "left"
        },
        {
          "to": "/docs/analise-financeira-tecnica",
          "label": "Analise",
          "position": "left"
        },
        {
          "to": "/docs/impacto",
          "label": "Impacto",
          "position": "left"
        },
        {
          "to": "/docs/equipe",
          "label": "Equipe",
          "position": "left"
        },
        {
          "to": "/docs/roadmap",
          "label": "Roadmap",
          "position": "left"
        },
        {
          "href": "https://github.com/DavidDeodato/vozsegura-docs",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentacao",
          "items": [
            {
              "label": "Sumario Executivo",
              "to": "/docs/index"
            },
            {
              "label": "Problema",
              "to": "/docs/entendimento-problema"
            },
            {
              "label": "Solucao",
              "to": "/docs/solucao"
            },
            {
              "label": "Analise",
              "to": "/docs/analise-financeira-tecnica"
            },
            {
              "label": "Impacto",
              "to": "/docs/impacto"
            },
            {
              "label": "Equipe",
              "to": "/docs/equipe"
            },
            {
              "label": "Roadmap",
              "to": "/docs/roadmap"
            }
          ]
        },
        {
          "title": "Mais",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/DavidDeodato/vozsegura-docs"
            }
          ]
        }
      ],
      "copyright": "© 2025 VozSegura"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "../docs",
          "routeBasePath": "docs",
          "sidebarPath": "C:\\Users\\pc\\OneDrive\\Desktop\\INTELI\\vozsegura-docs\\website\\sidebars.js",
          "editUrl": "https://github.com/DavidDeodato/vozsegura-docs/edit/main/"
        },
        "blog": false
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
